replicaCount: 2

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

productConfig: |
  # Your product configuration here
  
labels:
  product: "nginx-product"
  team: "dev-team"
  
nodeSelector: 
  dev_team: circle
  
resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
